### ISSUE TITLE
Wrong link to ESP8266 opensprinkler project

### ISSUE THREAD

**Issue by Hollol** [pbecchi/OpenSprinkler-Solar#1]
The link in "This project it is a branch from **Esp8266 OpenSprinkler** developed to add support to OS Bee 2.0 stations." is not working because it refers to a non-existing site on github.
I think the correct link is: https://github.com/pbecchi/OpenESP8266_Sprinkler.

By the way, will there be any update of your ESP8266 OpenSprinkler code?

Best, Lars

**Comment by pbecchi** [comment]
Thanks for your remark , I will correct the link immediately!
The new release of the Esp8266O0penSprinkler code , that will include support to OS Bee 2.0 and to my OpenSprinkler Solar is ready for upload, I was only waiting to test it on a real OS Bee 2.0 board.
Since you are interested I will upload today one beta release on the OpenSprinkler-Solar site.
This realized include also several bug correction as some minor improvement mainly related to WiFi connectivity.

**Comment by pbecchi** [comment]
Correction done

**Comment by Hollol** [comment]
Thanks for the upload. Indeed I am really interested in your project. I already ordered most of the necessary parts to build up my own ESP8266 OpenSprinkler system (based on a WeMos D1 mini ESP8266 board).
And now I can start ... :-)

**Comment by pbecchi** [comment]
Have a look to Open ESP8266 Sprinkler site, I have just uploaded a new branch that contain most recent release of the code for OS solar , OS Bee 2.0 and OS 3.0 ( do be done).
 Consider that README is still the old one and has not been updated .Better to use the one of this site,while  I am preparing a new one with a full explanation of the code mods!
